import io
import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from auth import get_current_user
from config import settings
from database import get_db
from models import DbBackup, User

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/admin", tags=["admin"])


async def _pg_dump(database_url: str) -> str:
    """Pure-Python PostgreSQL dump — no pg_dump binary needed."""
    import asyncpg

    # asyncpg uses postgresql:// not postgresql+asyncpg://
    dsn = database_url
    if "+asyncpg" in dsn:
        dsn = dsn.replace("postgresql+asyncpg://", "postgresql://")

    conn = await asyncpg.connect(dsn)
    try:
        buf = io.StringIO()
        now = datetime.now(timezone.utc).isoformat()
        buf.write(f"-- Bus Alert DB Backup — {now}\n")
        buf.write("-- Generated by Bus Alert v1.0\n\n")
        buf.write("SET client_encoding = 'UTF8';\n\n")

        tables: list[str] = [
            r["tablename"]
            for r in await conn.fetch(
                "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename"
            )
        ]

        for table in tables:
            buf.write(f"-- Table: {table}\n")
            rows = await conn.fetch(f'SELECT * FROM "{table}"')
            if not rows:
                buf.write(f"-- (empty)\n\n")
                continue

            cols = list(rows[0].keys())
            col_list = ", ".join(f'"{c}"' for c in cols)
            buf.write(f'DELETE FROM "{table}";\n')

            for row in rows:
                vals = []
                for v in row:
                    if v is None:
                        vals.append("NULL")
                    elif isinstance(v, bool):
                        vals.append("TRUE" if v else "FALSE")
                    elif isinstance(v, (int, float)):
                        vals.append(str(v))
                    elif isinstance(v, datetime):
                        vals.append(f"'{v.isoformat()}'")
                    else:
                        escaped = str(v).replace("'", "''")
                        vals.append(f"'{escaped}'")
                val_list = ", ".join(vals)
                buf.write(f'INSERT INTO "{table}" ({col_list}) VALUES ({val_list});\n')

            buf.write("\n")

        return buf.getvalue()
    finally:
        await conn.close()


def _sqlite_dump(database_url: str) -> str:
    import sqlite3

    db_path = database_url.replace("sqlite+aiosqlite:///", "").replace("sqlite:///", "")
    conn = sqlite3.connect(db_path)
    try:
        buf = io.StringIO()
        now = datetime.now(timezone.utc).isoformat()
        buf.write(f"-- Bus Alert DB Backup — {now}\n\n")
        for line in conn.iterdump():
            buf.write(f"{line}\n")
        return buf.getvalue()
    finally:
        conn.close()


@router.get("/backups")
async def list_backups(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List stored auto/manual backups (newest first)."""
    rows = (
        await db.scalars(
            select(DbBackup)
            .order_by(DbBackup.created_at.desc())
            .limit(7)
        )
    ).all()
    return [
        {
            "id": r.id,
            "trigger": r.trigger,
            "size_bytes": r.size_bytes,
            "created_at": r.created_at.isoformat(),
        }
        for r in rows
    ]


@router.post("/backups")
async def create_manual_backup(
    current_user: User = Depends(get_current_user),
):
    """Trigger a manual backup and persist it."""
    from services.auto_backup import run_backup
    b = await run_backup(trigger="manual")
    return {
        "id": b.id,
        "trigger": b.trigger,
        "size_bytes": b.size_bytes,
        "created_at": b.created_at.isoformat(),
    }


@router.get("/backups/{backup_id}/download")
async def download_stored_backup(
    backup_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download a previously stored backup."""
    row = await db.scalar(select(DbBackup).where(DbBackup.id == backup_id))
    if not row:
        raise HTTPException(status_code=404, detail="Backup not found")
    ts = row.created_at.strftime("%Y%m%d_%H%M%S")
    filename = f"busalert_backup_{ts}.sql"

    def _iter():
        yield row.sql_content.encode("utf-8")

    return StreamingResponse(
        _iter(),
        media_type="application/sql",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/db-backup")
async def download_backup(current_user: User = Depends(get_current_user)):
    """Download a full SQL backup of the database."""
    db_url = settings.async_database_url
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"busalert_backup_{timestamp}.sql"

    try:
        if "sqlite" in db_url:
            sql = _sqlite_dump(settings.database_url)
        else:
            sql = await _pg_dump(db_url)
    except Exception as exc:
        logger.exception("Backup failed: %s", exc)
        raise

    def iter_content():
        yield sql.encode("utf-8")

    return StreamingResponse(
        iter_content(),
        media_type="application/sql",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
